2020-02-15 18:49:00,356 - instabot version: 0.107.0 (bot) - INFO - Instabot version: 0.107.0 Started
2020-02-15 18:49:00,357 - instabot version: 0.107.0 (api_login) - INFO - PRE-LOGIN FLOW!... 
2020-02-15 18:49:10,658 - instabot version: 0.107.0 (api) - INFO - Logged-in successfully as 'dronevlieger'!
2020-02-15 18:49:10,659 - instabot version: 0.107.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: True
2020-02-15 18:49:17,840 - instabot version: 0.107.0 (api_login) - ERROR - Exception raised: 'API' object has no attribute 'bayan'
Traceback (most recent call last):
  File "/Users/niels/Documents/instabot/examples/../instabot/api/api_login.py", line 108, in login_flow
    check_flow.append(self.bayan())
AttributeError: 'API' object has no attribute 'bayan'

2020-02-15 18:49:17,840 - instabot version: 0.107.0 (bot_follow) - INFO - Follow followers of: fromwhereidrone
2020-02-15 18:49:24,276 - instabot version: 0.107.0 (api) - ERROR - Request returns 429 error!
2020-02-15 18:49:24,276 - instabot version: 0.107.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
2020-02-15 18:49:27,282 - instabot version: 0.107.0 (bot) - INFO - Total requests: 12
